apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      team: frontenddeveloper
  template:
    metadata:
      labels:
        team: frontenddeveloper
      annotations:
        group: javaboost
        email: java@java.com
        mobile: +90 532 532 0000
    spec:
      containers:
      - name: pod-bilgerest
        image: muhammedali55/bilgeweb:v001
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
          - containerPort: 80

