apiVersion: v1
kind: Pod
metadata:
  name: pod-bilgeweb
  labels:
    team: frontenddeveloper
  annotations:
    group: javaboost
    email: java@java.com
    mobile: +90 532 532 0000
spec:
  containers:
  - name: pod-bilgeweb
    image: muhammedali55/bilgeweb:v001
    resources:
      limits:
        memory: "1024Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
        hostPort: 9091
