spring:
  cloud:
    config:
      username: "administrator"
      password: "Bilge123!!"
      uri: "http://localhost:8888"
  config:
    import: "configserver:"
  application:
    name: user-service