server:
  port: 80

spring:
  security:
    user:
      name: admin
      password: root
  zipkin:
    enabled: true
    base-url: http://35.192.208.214:9411/
    service-name: user-service

s3:
  accesskey: ${S3AccessKey}
  secretkey: ${S3SecretKey}

logging:
  level:
    root: warn
    org.springframework.boot: info
    com.bilgeadam: debug
  file:
    name: webservice.log